[tool.black]
target-version = ["py311"]
line-length = 88
fast = true


[tool.flake8]
max-line-length = 88
select = "F,E,W,B,B901,B902,B903"
exclude = [
    ".eggs",
    ".git",
    ".tox",
    "nssm",
    "obj",
    "out",
    "packages",
    "pywin32",
    "tests",
    "swagger_client",
]
ignore = ["E722", "B001", "W503", "E203", "E731"]